"""职业方向归类：技术岗粗分类枚举（候选人 / JD 共用）。

用于精确筛选的「职业方向」硬性过滤与匹配，LLM 从固定枚举中选一，允许为空。
"""
from __future__ import annotations

DIRECTION_BACKEND = "BACKEND"
DIRECTION_FRONTEND = "FRONTEND"
DIRECTION_ALGORITHM = "ALGORITHM"
DIRECTION_DATA = "DATA"
DIRECTION_OPS = "OPS"
DIRECTION_QA = "QA"
DIRECTION_PRODUCT = "PRODUCT"
DIRECTION_MANAGEMENT = "MANAGEMENT"
DIRECTION_OTHER = "OTHER"

DIRECTIONS: tuple[str, ...] = (
    DIRECTION_BACKEND,
    DIRECTION_FRONTEND,
    DIRECTION_ALGORITHM,
    DIRECTION_DATA,
    DIRECTION_OPS,
    DIRECTION_QA,
    DIRECTION_PRODUCT,
    DIRECTION_MANAGEMENT,
    DIRECTION_OTHER,
)

DIRECTION_LABELS: dict[str, str] = {
    DIRECTION_BACKEND: "后端",
    DIRECTION_FRONTEND: "前端",
    DIRECTION_ALGORITHM: "算法",
    DIRECTION_DATA: "数据",
    DIRECTION_OPS: "运维",
    DIRECTION_QA: "测试",
    DIRECTION_PRODUCT: "产品",
    DIRECTION_MANAGEMENT: "管理",
    DIRECTION_OTHER: "其他",
}

# 学校属地（国内外高校筛选）：派生字段，从教育经历计算，非 LLM 解析。
SCHOOL_REGION_DOMESTIC = "domestic"
SCHOOL_REGION_OVERSEAS = "overseas"
