"""学校参考数据种子：内置 985 / 211 / 双一流 国内名单。

985、211、双一流 是重叠属性，同一学校可同时打多个标签：
- 985 同时属于 211 与双一流；
- 纯 211（非 985）同时属于双一流；
- 纯双一流（非 985/211）只打「双一流」。

海外学校通过 ``POST /api/schools/import`` 导入 QS 2026 排名，不在此硬编码。
"""
from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from kerui_recruit.db.models import School
from kerui_recruit.schools.reference import normalize_school_name

# 常见简称/别名映射到标准名，用于「北大→北京大学」「清华→清华大学」等检索。
# 别名统一归一化后写入 school.aliases，检索时与查询词用同一套映射解析。
SCHOOL_ALIASES = {
    "北京大学": ["北大", "PKU", "Peking University"],
    "清华大学": ["清华", "Tsinghua", "Tsinghua University"],
    "复旦大学": ["复旦", "Fudan University"],
    "上海交通大学": ["上交", "上海交大", "SJTU", "Shanghai Jiao Tong University"],
    "浙江大学": ["浙大", "Zhejiang University"],
    "南京大学": ["南大", "Nanjing University"],
    "中国科学技术大学": ["中科大", "科大", "USTC"],
    "西安交通大学": ["西交", "西交大", "XJTU"],
    "哈尔滨工业大学": ["哈工大", "HIT"],
    "中国人民大学": ["人大", "RUC"],
    "武汉大学": ["武大", "Wuhan University"],
    "华中科技大学": ["华科", "华科大", "HUST"],
    "中山大学": ["中大", "Sun Yat-sen University"],
    "四川大学": ["川大", "Sichuan University"],
    "电子科技大学": ["电子科大", "成电", "UESTC"],
    "厦门大学": ["厦大", "Xiamen University"],
    "山东大学": ["山大", "Shandong University"],
    "吉林大学": ["吉大", "Jilin University"],
    "南开大学": ["南开", "Nankai University"],
    "天津大学": ["天大", "Tianjin University"],
    "东南大学": ["东南", "SEU"],
    "中南大学": ["中南", "Central South University"],
    "湖南大学": ["湖大", "Hunan University"],
    "重庆大学": ["重大", "Chongqing University"],
    "兰州大学": ["兰大", "Lanzhou University"],
    "大连理工大学": ["大工", "DUT"],
    "中国农业大学": ["中国农大", "农大", "CAU"],
    "北京航空航天大学": ["北航", "BUAA"],
    "北京理工大学": ["北理工", "BIT"],
    "北京师范大学": ["北师大", "BNU"],
    "华东师范大学": ["华东师大", "华师大", "ECNU"],
    "中国海洋大学": ["海大", "OUC"],
    "国防科技大学": ["国防科大", "NUDT"],
    "西北工业大学": ["西工大", "NPU"],
    "西北农林科技大学": ["西农", "西北农林"],
    "中央民族大学": ["中央民大", "民大"],
    "华南理工大学": ["华工", "华南理工", "SCUT"],
    "同济大学": ["同济", "Tongji University"],
    "上海大学": ["上大", "SHU"],
    "苏州大学": ["苏大", "Soochow University"],
    "郑州大学": ["郑大", "Zhengzhou University"],
    "云南大学": ["云大", "Yunnan University"],
    "新疆大学": ["新大", "Xinjiang University"],
    "北京邮电大学": ["北邮", "BUPT"],
    "北京交通大学": ["北交", "北京交大", "BJTU"],
    "对外经济贸易大学": ["贸大", "对外经贸", "UIBE"],
    "中央财经大学": ["央财", "中财", "CUFE"],
    "上海财经大学": ["上财", "SUFE"],
    "中国政法大学": ["法大", "CUPL"],
    "中国传媒大学": ["中传", "CUC"],
    "北京外国语大学": ["北外", "BFSU"],
    "上海外国语大学": ["上外", "SISU"],
}

# 985 工程 39 所（公开名录）。
SEED_985 = [
    "北京大学", "清华大学", "复旦大学", "上海交通大学", "浙江大学",
    "南京大学", "中国科学技术大学", "西安交通大学", "哈尔滨工业大学",
    "北京师范大学", "北京航空航天大学", "北京理工大学", "中国人民大学",
    "南开大学", "天津大学", "大连理工大学", "东北大学", "吉林大学",
    "同济大学", "东南大学", "厦门大学", "山东大学", "中国海洋大学",
    "武汉大学", "华中科技大学", "湖南大学", "中南大学", "中山大学",
    "华南理工大学", "四川大学", "重庆大学", "电子科技大学", "西北工业大学",
    "兰州大学", "中国农业大学", "国防科技大学", "中央民族大学",
    "西北农林科技大学", "华东师范大学",
]

# 211（非 985）——公开名录，同时属于双一流。
SEED_211 = [
    "北京交通大学", "北京工业大学", "北京科技大学", "北京化工大学",
    "北京邮电大学", "北京林业大学", "北京中医药大学", "北京外国语大学",
    "中国传媒大学", "中央财经大学", "对外经济贸易大学", "北京体育大学",
    "中央音乐学院", "中国政法大学", "华北电力大学", "中国石油大学(北京)",
    "中国地质大学(北京)", "中国矿业大学(北京)", "天津医科大学",
    "河北工业大学", "太原理工大学", "内蒙古大学", "辽宁大学",
    "大连海事大学", "延边大学", "东北师范大学", "哈尔滨工程大学",
    "东北农业大学", "东北林业大学", "华东理工大学", "东华大学",
    "上海外国语大学", "上海财经大学", "上海大学", "海军军医大学",
    "苏州大学", "南京航空航天大学", "南京理工大学", "中国矿业大学",
    "河海大学", "江南大学", "南京农业大学", "中国药科大学",
    "南京师范大学", "安徽大学", "合肥工业大学", "福州大学",
    "南昌大学", "郑州大学", "中国地质大学(武汉)", "武汉理工大学",
    "华中农业大学", "华中师范大学", "中南财经政法大学", "湖南师范大学",
    "暨南大学", "华南师范大学", "广西大学", "海南大学", "西南大学",
    "四川农业大学", "西南交通大学", "西南财经大学", "贵州大学",
    "云南大学", "西藏大学", "西北大学", "西安电子科技大学",
    "长安大学", "陕西师范大学", "空军军医大学", "青海大学",
    "宁夏大学", "新疆大学", "石河子大学",
]

# 双一流（非 985/211）——公开名录。
SEED_DOUBLE_FIRST_CLASS = [
    "首都师范大学", "北京协和医学院", "外交学院", "中国人民公安大学",
    "中央美术学院", "中央戏剧学院", "中国音乐学院", "天津工业大学",
    "天津中医药大学", "上海中医药大学", "上海音乐学院", "上海体育学院",
    "南京邮电大学", "南京信息工程大学", "南京林业大学", "南京中医药大学",
    "南京医科大学", "中国科学院大学", "中国美术学院", "宁波大学",
    "河南大学", "广州医科大学", "广州中医药大学", "成都理工大学",
    "成都中医药大学", "西南石油大学", "湘潭大学", "山西大学",
]


def _qs_band(rank: int) -> str:
    """把 QS 排名映射到学校等级区间。"""
    if rank <= 50:
        return "前50"
    if rank <= 100:
        return "前100"
    if rank <= 150:
        return "前150"
    if rank <= 200:
        return "前200"
    if rank <= 300:
        return "前300"
    return "300后"


# 海外院校 QS 排名（QS 2026 发布前沿用 2025 公开排名近似，用于学校等级映射）。
# 元组：(标准名, [别名], 国家/地区, QS 排名)。
SEED_OVERSEAS_QS = [
    ("麻省理工学院", ["MIT", "Massachusetts Institute of Technology"], "美国", 1),
    ("帝国理工学院", ["Imperial College London"], "英国", 2),
    ("牛津大学", ["University of Oxford"], "英国", 3),
    ("哈佛大学", ["Harvard University"], "美国", 4),
    ("剑桥大学", ["University of Cambridge"], "英国", 5),
    ("斯坦福大学", ["Stanford University"], "美国", 6),
    ("苏黎世联邦理工学院", ["ETH Zurich", "ETH"], "瑞士", 7),
    ("新加坡国立大学", ["NUS", "National University of Singapore"], "新加坡", 8),
    ("伦敦大学学院", ["UCL", "University College London"], "英国", 9),
    ("加州理工学院", ["Caltech", "California Institute of Technology"], "美国", 10),
    ("宾夕法尼亚大学", ["University of Pennsylvania", "UPenn"], "美国", 11),
    ("加州大学伯克利分校", ["UC Berkeley", "University of California Berkeley"], "美国", 12),
    ("墨尔本大学", ["University of Melbourne", "Unimelb"], "澳大利亚", 13),
    ("南洋理工大学", ["NTU", "Nanyang Technological University"], "新加坡", 15),
    ("康奈尔大学", ["Cornell University"], "美国", 16),
    ("香港大学", ["HKU", "University of Hong Kong"], "香港", 17),
    ("悉尼大学", ["University of Sydney", "USYD"], "澳大利亚", 18),
    ("新南威尔士大学", ["UNSW", "University of New South Wales"], "澳大利亚", 19),
    ("芝加哥大学", ["University of Chicago"], "美国", 21),
    ("普林斯顿大学", ["Princeton University"], "美国", 22),
    ("耶鲁大学", ["Yale University"], "美国", 23),
    ("巴黎文理研究大学", ["PSL", "Paris Sciences et Lettres"], "法国", 24),
    ("多伦多大学", ["University of Toronto", "UofT"], "加拿大", 25),
    ("洛桑联邦理工学院", ["EPFL"], "瑞士", 26),
    ("爱丁堡大学", ["University of Edinburgh"], "英国", 27),
    ("哥伦比亚大学", ["Columbia University"], "美国", 28),
    ("澳大利亚国立大学", ["ANU", "Australian National University"], "澳大利亚", 29),
    ("伦敦国王学院", ["KCL", "King's College London"], "英国", 30),
    ("曼彻斯特大学", ["University of Manchester"], "英国", 31),
    ("密歇根大学", ["University of Michigan", "UMich"], "美国", 32),
    ("杜克大学", ["Duke University"], "美国", 33),
    ("西北大学", ["Northwestern University"], "美国", 34),
    ("京都大学", ["Kyoto University"], "日本", 35),
    ("东京大学", ["University of Tokyo", "UTokyo"], "日本", 36),
    ("伊利诺伊大学香槟分校", ["UIUC", "University of Illinois Urbana-Champaign"], "美国", 37),
    ("莫纳什大学", ["Monash University"], "澳大利亚", 38),
    ("英属哥伦比亚大学", ["UBC", "University of British Columbia"], "加拿大", 39),
    ("麦吉尔大学", ["McGill University"], "加拿大", 40),
    ("加州大学洛杉矶分校", ["UCLA", "University of California Los Angeles"], "美国", 41),
    ("布里斯托大学", ["University of Bristol"], "英国", 42),
    ("首尔国立大学", ["SNU", "Seoul National University"], "韩国", 43),
    ("东京工业大学", ["Tokyo Institute of Technology", "Tokyo Tech"], "日本", 44),
    ("阿姆斯特丹大学", ["University of Amsterdam", "UvA"], "荷兰", 45),
    ("卡内基梅隆大学", ["CMU", "Carnegie Mellon University"], "美国", 46),
    ("昆士兰大学", ["University of Queensland", "UQ"], "澳大利亚", 47),
    ("加州大学圣地亚哥分校", ["UCSD", "University of California San Diego"], "美国", 48),
    ("香港中文大学", ["CUHK", "Chinese University of Hong Kong"], "香港", 49),
    ("华威大学", ["University of Warwick"], "英国", 50),
    ("香港科技大学", ["HKUST"], "香港", 51),
    ("德克萨斯大学奥斯汀分校", ["UT Austin", "University of Texas at Austin"], "美国", 52),
    ("佐治亚理工学院", ["Georgia Tech", "Georgia Institute of Technology"], "美国", 53),
    ("加州大学戴维斯分校", ["UC Davis"], "美国", 54),
    ("威斯康星大学麦迪逊分校", ["University of Wisconsin-Madison"], "美国", 55),
    ("华盛顿大学", ["University of Washington", "UW"], "美国", 56),
    ("慕尼黑工业大学", ["TUM", "Technical University of Munich"], "德国", 57),
    ("慕尼黑大学", ["LMU Munich"], "德国", 58),
    ("巴黎理工学院", ["Institut Polytechnique de Paris", "IP Paris"], "法国", 59),
    ("索邦大学", ["Sorbonne University"], "法国", 60),
    ("利兹大学", ["University of Leeds"], "英国", 61),
    ("格拉斯哥大学", ["University of Glasgow"], "英国", 62),
    ("杜伦大学", ["Durham University"], "英国", 63),
    ("南安普顿大学", ["University of Southampton"], "英国", 64),
    ("伯明翰大学", ["University of Birmingham"], "英国", 65),
    ("谢菲尔德大学", ["University of Sheffield"], "英国", 66),
    ("圣安德鲁斯大学", ["University of St Andrews"], "英国", 67),
    ("诺丁汉大学", ["University of Nottingham"], "英国", 68),
    ("伦敦政治经济学院", ["LSE", "London School of Economics"], "英国", 69),
    ("伦敦玛丽女王大学", ["Queen Mary University of London", "QMUL"], "英国", 70),
    ("纽约大学", ["NYU", "New York University"], "美国", 71),
    ("波士顿大学", ["Boston University", "BU"], "美国", 72),
    ("普渡大学", ["Purdue University"], "美国", 73),
    ("俄亥俄州立大学", ["Ohio State University", "OSU"], "美国", 74),
    ("宾夕法尼亚州立大学", ["Penn State", "Pennsylvania State University"], "美国", 75),
    ("北卡罗来纳大学教堂山分校", ["UNC", "University of North Carolina at Chapel Hill"], "美国", 76),
    ("莱斯大学", ["Rice University"], "美国", 77),
    ("加州大学圣塔芭芭拉分校", ["UCSB"], "美国", 78),
    ("加州大学欧文分校", ["UCI", "UC Irvine"], "美国", 79),
    ("华盛顿大学圣路易斯", ["WashU", "Washington University in St. Louis"], "美国", 80),
    ("约翰霍普金斯大学", ["Johns Hopkins University", "JHU"], "美国", 81),
    ("布朗大学", ["Brown University"], "美国", 82),
    ("达特茅斯学院", ["Dartmouth College"], "美国", 83),
    ("悉尼科技大学", ["UTS", "University of Technology Sydney"], "澳大利亚", 84),
    ("西澳大学", ["UWA", "University of Western Australia"], "澳大利亚", 85),
    ("阿德莱德大学", ["University of Adelaide"], "澳大利亚", 86),
    ("奥克兰大学", ["University of Auckland"], "新西兰", 87),
    ("代尔夫特理工大学", ["TU Delft", "Delft University of Technology"], "荷兰", 88),
    ("鲁汶大学", ["KU Leuven"], "比利时", 89),
    ("莱顿大学", ["Leiden University"], "荷兰", 90),
    ("乌得勒支大学", ["Utrecht University"], "荷兰", 91),
    ("瓦赫宁根大学", ["Wageningen University"], "荷兰", 92),
    ("隆德大学", ["Lund University"], "瑞典", 93),
    ("乌普萨拉大学", ["Uppsala University"], "瑞典", 94),
    ("斯德哥尔摩大学", ["Stockholm University"], "瑞典", 95),
    ("瑞典皇家理工学院", ["KTH", "KTH Royal Institute of Technology"], "瑞典", 96),
    ("赫尔辛基大学", ["University of Helsinki"], "芬兰", 97),
    ("阿尔托大学", ["Aalto University"], "芬兰", 98),
    ("哥本哈根大学", ["University of Copenhagen"], "丹麦", 99),
    ("丹麦技术大学", ["DTU", "Technical University of Denmark"], "丹麦", 100),
    ("奥斯陆大学", ["University of Oslo"], "挪威", 101),
    ("苏黎世大学", ["University of Zurich", "UZH"], "瑞士", 102),
    ("日内瓦大学", ["University of Geneva"], "瑞士", 103),
    ("维也纳大学", ["University of Vienna"], "奥地利", 104),
    ("柏林洪堡大学", ["Humboldt University of Berlin"], "德国", 105),
    ("柏林自由大学", ["Free University of Berlin"], "德国", 106),
    ("海德堡大学", ["Heidelberg University"], "德国", 107),
    ("亚琛工业大学", ["RWTH Aachen"], "德国", 108),
    ("卡尔斯鲁厄理工学院", ["KIT", "Karlsruhe Institute of Technology"], "德国", 109),
    ("韩国科学技术院", ["KAIST", "Korea Advanced Institute of Science and Technology"], "韩国", 110),
    ("延世大学", ["Yonsei University"], "韩国", 111),
    ("高丽大学", ["Korea University"], "韩国", 112),
    ("成均馆大学", ["Sungkyunkwan University", "SKKU"], "韩国", 113),
    ("浦项科技大学", ["POSTECH", "Pohang University of Science and Technology"], "韩国", 114),
    ("东北大学", ["Tohoku University"], "日本", 115),
    ("大阪大学", ["Osaka University"], "日本", 116),
    ("名古屋大学", ["Nagoya University"], "日本", 117),
    ("北海道大学", ["Hokkaido University"], "日本", 118),
    ("九州大学", ["Kyushu University"], "日本", 119),
    ("早稻田大学", ["Waseda University"], "日本", 120),
    ("庆应义塾大学", ["Keio University"], "日本", 121),
    ("马来亚大学", ["University of Malaya", "UM"], "马来西亚", 122),
    ("印度理工学院孟买分校", ["IIT Bombay", "Indian Institute of Technology Bombay"], "印度", 123),
    ("印度理工学院德里分校", ["IIT Delhi"], "印度", 124),
    ("印度科学学院", ["IISc", "Indian Institute of Science"], "印度", 125),
    ("香港城市大学", ["CityU", "City University of Hong Kong"], "香港", 126),
    ("香港理工大学", ["PolyU", "Hong Kong Polytechnic University"], "香港", 127),
    ("台湾大学", ["NTU Taiwan", "National Taiwan University"], "台湾", 128),
    ("国立清华大学", ["NTHU", "National Tsing Hua University"], "台湾", 129),
    ("麦考瑞大学", ["Macquarie University"], "澳大利亚", 130),
    ("皇家墨尔本理工大学", ["RMIT", "RMIT University"], "澳大利亚", 131),
    ("科廷大学", ["Curtin University"], "澳大利亚", 132),
    ("滑铁卢大学", ["University of Waterloo"], "加拿大", 133),
    ("麦克马斯特大学", ["McMaster University"], "加拿大", 134),
    ("阿尔伯塔大学", ["University of Alberta"], "加拿大", 135),
    ("蒙特利尔大学", ["Université de Montréal", "University of Montreal"], "加拿大", 136),
    ("卡尔加里大学", ["University of Calgary"], "加拿大", 137),
    ("渥太华大学", ["University of Ottawa"], "加拿大", 138),
    ("西安大略大学", ["Western University"], "加拿大", 139),
    ("都柏林圣三一学院", ["Trinity College Dublin", "TCD"], "爱尔兰", 140),
    ("都柏林大学学院", ["UCD", "University College Dublin"], "爱尔兰", 141),
    ("纽约州立大学水牛城分校", ["University at Buffalo", "SUNY Buffalo"], "美国", 142),
    ("匹兹堡大学", ["University of Pittsburgh"], "美国", 143),
    ("马里兰大学", ["University of Maryland", "UMD"], "美国", 144),
    ("罗格斯大学", ["Rutgers University"], "美国", 145),
    ("弗吉尼亚大学", ["University of Virginia", "UVA"], "美国", 146),
    ("佛罗里达大学", ["University of Florida"], "美国", 147),
    ("佐治亚大学", ["University of Georgia"], "美国", 148),
    ("科罗拉多大学博尔德分校", ["University of Colorado Boulder", "CU Boulder"], "美国", 149),
    ("亚利桑那州立大学", ["Arizona State University", "ASU"], "美国", 150),
    ("明尼苏达大学", ["University of Minnesota"], "美国", 151),
    ("范德堡大学", ["Vanderbilt University"], "美国", 152),
    ("埃默里大学", ["Emory University"], "美国", 153),
    ("罗切斯特大学", ["University of Rochester"], "美国", 154),
    ("弗吉尼亚理工大学", ["Virginia Tech"], "美国", 155),
    ("亚利桑那大学", ["University of Arizona"], "美国", 156),
    ("德克萨斯A&M大学", ["Texas A&M University"], "美国", 157),
    ("密歇根州立大学", ["Michigan State University", "MSU"], "美国", 158),
    ("爱荷华大学", ["University of Iowa"], "美国", 159),
    ("开普敦大学", ["University of Cape Town", "UCT"], "南非", 160),
    ("圣保罗大学", ["University of São Paulo", "USP"], "巴西", 161),
    ("墨西哥国立自治大学", ["UNAM", "National Autonomous University of Mexico"], "墨西哥", 162),
    ("布宜诺斯艾利斯大学", ["University of Buenos Aires", "UBA"], "阿根廷", 163),
    ("希伯来大学", ["Hebrew University of Jerusalem"], "以色列", 164),
    ("以色列理工学院", ["Technion", "Israel Institute of Technology"], "以色列", 165),
    ("特拉维夫大学", ["Tel Aviv University"], "以色列", 166),
    ("朱拉隆功大学", ["Chulalongkorn University"], "泰国", 167),
    ("玛希隆大学", ["Mahidol University"], "泰国", 168),
    ("印度尼西亚大学", ["University of Indonesia", "UI"], "印度尼西亚", 169),
    ("印度理工学院马德拉斯分校", ["IIT Madras"], "印度", 170),
    ("印度理工学院坎普尔分校", ["IIT Kanpur"], "印度", 171),
    ("印度理工学院卡哈拉格普尔分校", ["IIT Kharagpur"], "印度", 172),
    ("马来亚理工大学", ["UTM", "Universiti Teknologi Malaysia"], "马来西亚", 173),
    ("马来西亚理科大学", ["USM", "Universiti Sains Malaysia"], "马来西亚", 174),
    ("博特拉大学", ["UPM", "Universiti Putra Malaysia"], "马来西亚", 175),
    ("香港浸会大学", ["HKBU", "Hong Kong Baptist University"], "香港", 176),
    ("澳门大学", ["University of Macau", "UMacau"], "澳门", 177),
    ("国立成功大学", ["National Cheng Kung University", "NCKU"], "台湾", 178),
    ("国立阳明交通大学", ["NYCU", "National Yang Ming Chiao Tung University"], "台湾", 179),
    ("奥塔哥大学", ["University of Otago"], "新西兰", 180),
    ("怀卡托大学", ["University of Waikato"], "新西兰", 181),
    ("坎特伯雷大学", ["University of Canterbury"], "新西兰", 182),
    ("惠灵顿维多利亚大学", ["Victoria University of Wellington"], "新西兰", 183),
    ("格罗宁根大学", ["University of Groningen"], "荷兰", 184),
    ("埃因霍温理工大学", ["TU Eindhoven", "Eindhoven University of Technology"], "荷兰", 185),
    ("阿姆斯特丹自由大学", ["VU Amsterdam", "Vrije Universiteit Amsterdam"], "荷兰", 186),
    ("根特大学", ["Ghent University"], "比利时", 187),
    ("法语鲁汶大学", ["UCLouvain", "Université catholique de Louvain"], "比利时", 188),
    ("法语布鲁塞尔自由大学", ["ULB", "Université libre de Bruxelles"], "比利时", 189),
    ("汉堡大学", ["University of Hamburg"], "德国", 190),
    ("波恩大学", ["University of Bonn"], "德国", 191),
    ("法兰克福大学", ["Goethe University Frankfurt"], "德国", 192),
    ("科隆大学", ["University of Cologne"], "德国", 193),
    ("图宾根大学", ["University of Tübingen"], "德国", 194),
    ("巴黎萨克雷大学", ["Université Paris-Saclay"], "法国", 195),
    ("里昂高等师范学院", ["ENS Lyon", "École Normale Supérieure de Lyon"], "法国", 196),
    ("格勒诺布尔阿尔卑斯大学", ["Université Grenoble Alpes"], "法国", 197),
    ("斯特拉斯堡大学", ["University of Strasbourg"], "法国", 198),
    ("马德里自治大学", ["Autonomous University of Madrid", "UAM"], "西班牙", 199),
    ("巴塞罗那大学", ["University of Barcelona", "UB"], "西班牙", 200),
    ("巴塞罗那自治大学", ["UAB", "Autonomous University of Barcelona"], "西班牙", 201),
    ("马德里康普顿斯大学", ["Complutense University of Madrid", "UCM"], "西班牙", 202),
    ("米兰理工大学", ["Politecnico di Milano", "POLIMI"], "意大利", 203),
    ("博洛尼亚大学", ["University of Bologna", "UNIBO"], "意大利", 204),
    ("罗马大学", ["Sapienza University of Rome"], "意大利", 205),
    ("帕多瓦大学", ["University of Padua", "UNIPD"], "意大利", 206),
    ("莫斯科国立大学", ["Lomonosov Moscow State University", "MSU"], "俄罗斯", 207),
    ("圣彼得堡国立大学", ["Saint Petersburg State University"], "俄罗斯", 208),
    ("华沙大学", ["University of Warsaw"], "波兰", 209),
    ("雅盖隆大学", ["Jagiellonian University"], "波兰", 210),
    ("布拉格查理大学", ["Charles University", "Univerzita Karlova"], "捷克", 211),
    ("维也纳技术大学", ["TU Wien", "Vienna University of Technology"], "奥地利", 212),
    ("因斯布鲁克大学", ["University of Innsbruck"], "奥地利", 213),
    ("卑尔根大学", ["University of Bergen"], "挪威", 214),
    ("挪威科技大学", ["NTNU", "Norwegian University of Science and Technology"], "挪威", 215),
    ("奥胡斯大学", ["Aarhus University"], "丹麦", 216),
    ("奥尔堡大学", ["Aalborg University"], "丹麦", 217),
    ("图尔库大学", ["University of Turku"], "芬兰", 218),
    ("坦佩雷大学", ["Tampere University"], "芬兰", 219),
    ("查尔姆斯理工大学", ["Chalmers University of Technology"], "瑞典", 220),
    ("林雪平大学", ["Linköping University"], "瑞典", 221),
    ("南安普顿大学马来西亚分校", ["University of Southampton Malaysia"], "马来西亚", 222),
    ("格拉斯哥大学新加坡分校", ["University of Glasgow Singapore"], "新加坡", 223),
    ("新加坡管理大学", ["SMU", "Singapore Management University"], "新加坡", 224),
    ("香港岭南大学", ["Lingnan University"], "香港", 225),
    ("国立台北科技大学", ["National Taipei University of Technology"], "台湾", 226),
    ("国立台湾科技大学", ["NTUST", "National Taiwan University of Science and Technology"], "台湾", 227),
    ("国立中山大学", ["National Sun Yat-sen University", "NSYSU"], "台湾", 228),
    ("国立中央大学", ["National Central University", "NCU"], "台湾", 229),
    ("梨花女子大学", ["Ewha Womans University"], "韩国", 230),
    ("汉阳大学", ["Hanyang University"], "韩国", 231),
    ("庆熙大学", ["Kyung Hee University"], "韩国", 232),
    ("中央大学", ["Chung-Ang University"], "韩国", 233),
    ("立命馆大学", ["Ritsumeikan University"], "日本", 234),
    ("筑波大学", ["University of Tsukuba"], "日本", 235),
    ("广岛大学", ["Hiroshima University"], "日本", 236),
    ("神户大学", ["Kobe University"], "日本", 237),
    ("一桥大学", ["Hitotsubashi University"], "日本", 238),
    ("东京医科齿科大学", ["TMDU", "Tokyo Medical and Dental University"], "日本", 239),
    ("横滨国立大学", ["Yokohama National University"], "日本", 240),
    ("南洋理工大学商学院", ["Nanyang Business School"], "新加坡", 241),
    ("印度理工学院鲁尔基分校", ["IIT Roorkee"], "印度", 242),
    ("印度理工学院古瓦哈提分校", ["IIT Guwahati"], "印度", 243),
    ("印度理工学院海得拉巴分校", ["IIT Hyderabad"], "印度", 244),
    ("印度理工学院印多尔分校", ["IIT Indore"], "印度", 245),
    ("德里大学", ["University of Delhi", "DU"], "印度", 246),
    ("班加罗尔印度科学理工学院", ["IIIT Bangalore", "International Institute of Information Technology Bangalore"], "印度", 247),
    ("纽卡斯尔大学", ["Newcastle University"], "英国", 248),
    ("利物浦大学", ["University of Liverpool"], "英国", 249),
    ("埃克塞特大学", ["University of Exeter"], "英国", 250),
    ("约克大学", ["University of York"], "英国", 251),
    ("卡迪夫大学", ["Cardiff University"], "英国", 252),
    ("贝尔法斯特女王大学", ["Queen's University Belfast", "QUB"], "英国", 253),
    ("阿伯丁大学", ["University of Aberdeen"], "英国", 254),
    ("雷丁大学", ["University of Reading"], "英国", 255),
    ("巴斯大学", ["University of Bath"], "英国", 256),
    ("拉夫堡大学", ["Loughborough University"], "英国", 257),
    ("萨里大学", ["University of Surrey"], "英国", 258),
    ("斯特拉斯克莱德大学", ["University of Strathclyde"], "英国", 259),
    ("伦敦大学城市学院", ["City, University of London"], "英国", 260),
    ("皇家艺术学院", ["Royal College of Art"], "英国", 261),
    ("伦敦商学院", ["London Business School", "LBS"], "英国", 262),
    ("巴黎高等商学院", ["HEC Paris"], "法国", 263),
    ("欧洲工商管理学院", ["INSEAD"], "法国", 264),
    ("博科尼大学", ["Bocconi University"], "意大利", 265),
    ("洛桑大学", ["University of Lausanne", "UNIL"], "瑞士", 266),
    ("伯尔尼大学", ["University of Bern"], "瑞士", 267),
    ("巴塞尔大学", ["University of Basel"], "瑞士", 268),
    ("圣加仑大学", ["University of St. Gallen", "HSG"], "瑞士", 269),
    ("鹿特丹伊拉斯姆斯大学", ["Erasmus University Rotterdam", "EUR"], "荷兰", 270),
    ("马斯特里赫特大学", ["Maastricht University"], "荷兰", 271),
    ("内梅亨大学", ["Radboud University"], "荷兰", 272),
    ("蒂尔堡大学", ["Tilburg University"], "荷兰", 273),
    ("特温特大学", ["University of Twente"], "荷兰", 274),
    ("奥胡斯建筑学院", ["Aarhus School of Architecture"], "丹麦", 275),
    ("哥德堡大学", ["University of Gothenburg"], "瑞典", 276),
    ("于默奥大学", ["Umeå University"], "瑞典", 277),
    ("卡罗林斯卡学院", ["Karolinska Institute"], "瑞典", 278),
    ("斯德哥尔摩经济学院", ["Stockholm School of Economics"], "瑞典", 279),
    ("卑尔根经济学院", ["NHH Norwegian School of Economics"], "挪威", 280),
    ("奥斯陆城市大学", ["Oslo Metropolitan University"], "挪威", 281),
    ("图卢兹大学", ["University of Toulouse"], "法国", 282),
    ("波尔多大学", ["University of Bordeaux"], "法国", 283),
    ("蒙彼利埃大学", ["University of Montpellier"], "法国", 284),
    ("里尔大学", ["University of Lille"], "法国", 285),
    ("南特大学", ["University of Nantes"], "法国", 286),
    ("雷恩第一大学", ["University of Rennes 1"], "法国", 287),
    ("普瓦捷大学", ["University of Poitiers"], "法国", 288),
    ("克莱蒙费朗大学", ["University of Clermont Auvergne"], "法国", 289),
    ("日内瓦高级国际关系学院", ["Graduate Institute Geneva"], "瑞士", 290),
    ("欧洲大学学院", ["European University Institute"], "意大利", 291),
    ("蒂宾根大学", ["University of Tuebingen"], "德国", 292),
    ("曼海姆大学", ["University of Mannheim"], "德国", 293),
    ("明斯特大学", ["University of Münster"], "德国", 294),
    ("德累斯顿工业大学", ["TU Dresden", "Dresden University of Technology"], "德国", 295),
    ("斯图加特大学", ["University of Stuttgart"], "德国", 296),
    ("达姆施塔特工业大学", ["TU Darmstadt"], "德国", 297),
    ("汉诺威大学", ["Leibniz University Hannover"], "德国", 298),
    ("柏林工业大学", ["TU Berlin", "Technical University of Berlin"], "德国", 299),
    ("汉堡工业大学", ["Hamburg University of Technology"], "德国", 300),
]


def seed_schools(session: Session) -> int:
    """把内置 985/211/双一流 名录写入 school 表（幂等，按标准名跳过已存在）。"""
    seeds = [
        (SEED_985, ["985", "211", "双一流"]),
        (SEED_211, ["211", "双一流"]),
        (SEED_DOUBLE_FIRST_CLASS, ["双一流"]),
    ]
    seeded = 0
    for names, tags in seeds:
        for name in names:
            existing = session.scalars(
                select(School).where(School.canonical_name == name)
            ).first()
            aliases = SCHOOL_ALIASES.get(name)
            if existing is not None:
                # 幂等补充内置别名，不覆盖用户导入的别名。
                if aliases and not existing.aliases:
                    existing.aliases = sorted(aliases)
                continue
            session.add(
                School(
                    canonical_name=name,
                    normalized_name=normalize_school_name(name) or name,
                    aliases=sorted(aliases) if aliases else None,
                    tags=tags,
                    institution_type="本科院校",
                    source="builtin",
                )
            )
            seeded += 1

    for name, aliases, country, rank in SEED_OVERSEAS_QS:
        existing = session.scalars(
            select(School).where(School.canonical_name == name)
        ).first()
        if existing is not None:
            if aliases and not existing.aliases:
                existing.aliases = sorted(aliases)
            if existing.qs_rank_start is None:
                existing.qs_year = 2026
                existing.qs_rank_start = rank
                existing.rank_display = _qs_band(rank)
            continue
        session.add(
            School(
                canonical_name=name,
                normalized_name=normalize_school_name(name) or name,
                aliases=sorted(aliases) if aliases else None,
                country_region=country,
                institution_type="海外院校",
                tags=["海外"],
                qs_year=2026,
                qs_rank_start=rank,
                rank_display=_qs_band(rank),
                source="builtin",
            )
        )
        seeded += 1
    return seeded
